### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/obs-cr#1]
(these are possibly intermingled)
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
Exception in Tkinter callback
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rkdarst/git/obs-coderefinery-control/control.py", line 94, in run
    pip_size.update(pip_size.last_state)
  File "/home/rkdarst/git/obs-coderefinery-control/control.py", line 244, in update
Traceback (most recent call last):
    id_ = cl1.get_scene_item_id(scene, PIP).scene_item_id
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tkinter/__init__.py", line 861, in callit
    func(*args)
AttributeError: type object 'GetMediaInputStatusDataclass' has no attribute 'scene_item_transform'
  File "/home/rkdarst/git/obs-coderefinery-control/control.py", line 292, in update_timer
    event = cl1.get_media_input_status(self.input_name)
               ^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'GetSceneItemTransformDataclass' has no attribute 'media_duration'
```

**Comment by rkdarst** [comment]
I hope this is solved now. Many things have been changed since then.
