### ISSUE TITLE
traceback (scene_item_transform)

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/obs-cr#7]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tkinter/__init__.py", line 861, in callit
    func(*args)
  File "/home/rkdarst/git/obs-cr/obs_cr/control.py", line 719, in update_gallery_size
    self.obs_update(obsreq.get_scene_item_transform(NOTES, self.gallery_id).scene_item_transform['scaleX'])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'scene_item_transform'
```

**Comment by rkdarst** [comment]
This didn't affect anything else, the control panel keeps running.

I think this might be adjusting the gallery size on as scene that doesn't have a gallery visible

**Comment by rkdarst** [comment]
The local application is basically deprecated now so not much is needed now.
